#!/bin/bash

printf "compiling Commnad-T...\n"
cd ~/.vim/bundle/Command-T/ruby/command-t
ruby extconf.rb
make clean
make

printf "updating snippets...\n"
mv -u ~/.vim/bundle/snipmate.vim/snippets/* ~/.vim/snippets
rm ~/.vim/bundle/snipmate.vim/snippets/*

printf "done.\n"
