#!/bin/bash
git submodule foreach git pull origin master

printf "\n\e[1;32mWill now compile Commnad-T...\e[0m\n\n"
cd ~/.vim/bundle/commandt/ruby/command-t
ruby extconf.rb
make

printf "\n\e[1;32mWill now update snippets...\e[0m\n\n"
mv -nu ~/.vim/bundle/snipmate/snippets/* ~/.vim/snippets
rm ~/.vim/bundle/snippets/*
